package sqlbuilder

const (
	LIKE          = "like"
	NLIKE         = "not like"
	START_WITH    = "start with"
	NSTART_WITH   = "not start with"
	END_WITH      = "end with"
	NEND_WITH     = "not end with"
	IN            = "in"
	NIN           = "not in"
	BETWEEN       = "between"
	NBETWEEN      = "not between"
	EQUAL         = "="
	NEQUAL        = "!="
	GT            = ">"
	LT            = "<"
	GTE           = ">="
	LTE           = "<="
	IS_NULL       = "is null"
	IS_NOT_NULL   = "is not null"
	IS_EMPTY      = "is empty"
	IS_NOT_EMPTY  = "is not empty"
	EXISTS        = "exists"
	NOT_EXISTS    = "not exists"
	FIND_IN_SET   = "find in set"
	JSON_EXTRACT  = "json_extract"
	MULTI_IN      = "multi in"
	MULTI_NIN     = "multi not in"
)
